name: ${project.artifactId}
main: net.terrocidepvp.legacypotions.LegacyPotions
version: ${project.version}
authors: [Terrobility, Byteflux]
description: ${project.description}
website: http://www.terrocidepvp.net/
